#defaultView:PieChart
#title: Könsfördelning som cirkeldiagram

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?label (COUNT(?person) AS ?count) WHERE {
  ?person a <http://schema.org/Person> .
  ?person skos:prefLabel ?name .
  ?person foaf:gender ?label .
}
GROUP BY ?label